/**
 * Type Definitions for Demo Data Generator
 * 
 * This file contains TypeScript interfaces that define the structure
 * of all data types generated by the application. These interfaces
 * ensure type safety and provide clear documentation of the data
 * structures used throughout the system.
 */

/**
 * User Interface
 * 
 * Represents a user profile with personal information and address details.
 * This interface is used for generating realistic user data with country-specific
 * information and demographic details.
 * 
 * @property id - Unique identifier for the user
 * @property firstName - User's first name
 * @property lastName - User's last name
 * @property email - User's email address (uses mediarithmics.com domain)
 * @property email_hash - SHA256 hash of the email address for privacy compliance
 * @property phone - User's phone number (optional - not currently generated)
 * @property address - Complete address information
 * @property createdAt - Timestamp when the user profile was created
 */
export interface User {
  id: string;
  firstName: string;
  lastName: string;
  email: string;
  email_hash: string;
  phone?: string; // Optional field - not currently generated in the application
  address: {
    street: string;
    city: string;
    state: string;
    zipCode: string;
    country: string;
  };
  createdAt: Date;
}

/**
 * Product Interface
 * 
 * Represents a product in an e-commerce catalog with all necessary
 * information for product management and display.
 * 
 * @property id - Unique identifier for the product
 * @property name - Product name/title
 * @property description - Detailed product description
 * @property price - Product price as a number
 * @property category - Product category for organization
 * @property inStock - Whether the product is currently in stock
 * @property tags - Array of tags for categorization and search
 * @property createdAt - Timestamp when the product was added to catalog
 */
export interface Product {
  id: string;
  name: string;
  description: string;
  price: number;
  category: string;
  inStock: boolean;
  tags: string[];
  createdAt: Date;
}

/**
 * Event Types
 * 
 * Defines all supported event types for user interactions and tracking.
 * These event types cover various user behaviors across web, mobile, and
 * marketing channels.
 */
export type EventType = 
  | 'page_view'
  | 'search'
  | 'article_view'
  | 'video_view'
  | 'audio_listen'
  | 'ad_view'
  | 'ad_click'
  | 'email_open'
  | 'email_click'
  | 'add_itemToCart'
  | 'remove_itemFromCart'
  | 'transaction_complete'
  | 'checkout'
  | 'view_cart'
  | 'richpush_open'
  | 'richpush_click';

/**
 * MixedDataItem Interface
 * 
 * Represents a generic data item that can contain different types of
 * business entities. This interface is used by the DataGenerator to
 * create diverse datasets containing users, products, orders, reviews,
 * and anonymous events.
 * 
 * @property id - Unique identifier for the data item
 * @property type - The type of data contained in this item
 * @property description - Human-readable description of the item
 * @property data - The actual data object (varies by type)
 * @property createdAt - Timestamp when the item was created
 * 
 * Supported types:
 * - 'user': Contains a User object
 * - 'product': Contains a Product object
 * - 'order': Contains order data (Record<string, unknown>)
 * - 'review': Contains review data (Record<string, unknown>)
 * - 'anonymous_event': Contains anonymous event data (Record<string, unknown>)
 */
export interface MixedDataItem {
  id: string;
  type: 'user' | 'product' | 'order' | 'review' | 'anonymous_event';
  description: string;
  data: User | Product | Record<string, unknown>;
  createdAt: Date;
} 